/**
 * GSD Command Registration
 *
 * Discovers all GSD command .md files and registers them as Pi extension
 * commands (/gsd:name). Each command handler reads the .md template,
 * strips frontmatter, rewrites paths, injects arguments, and sends
 * as a user message.
 *
 * Generated by pi-gsd-maker.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { GsdPathResolver } from "./path-resolver.js";

interface CommandMeta {
  name: string;
  description: string;
  argumentHint: string;
  body: string;
}

/**
 * Parse GSD command frontmatter.
 * GSD commands use YAML frontmatter with name, description, allowed-tools, etc.
 */
function parseCommand(content: string): CommandMeta {
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!fmMatch) {
    return { name: "", description: "", argumentHint: "", body: content };
  }

  const fm = fmMatch[1];
  const body = fmMatch[2];

  const nameMatch = fm.match(/^name:\s*(.+)$/m);
  const descMatch = fm.match(/^description:\s*(.+)$/m);
  const argHintMatch = fm.match(/^argument-hint:\s*(.+)$/m);

  return {
    name: nameMatch?.[1]?.trim().replace(/^["']|["']$/g, "") ?? "",
    description: descMatch?.[1]?.trim().replace(/^["']|["']$/g, "") ?? "",
    argumentHint:
      argHintMatch?.[1]?.trim().replace(/^["']|["']$/g, "") ?? "",
    body,
  };
}

/**
 * Register all GSD commands found in commands/gsd/*.md.
 *
 * Each file like plan-phase.md becomes /gsd:plan-phase.
 * The command handler:
 *   1. Re-reads the .md file (allows hot-reload via /reload)
 *   2. Applies full path resolution + argument injection
 *   3. Sends the transformed prompt as a user message
 *
 * Also registers bare /gsd command (reads help.md).
 */
export function registerGsdCommands(
  pi: any,
  resolver: GsdPathResolver
): number {
  const commandsDir = path.join(resolver.packageRoot, "commands", "gsd");

  // Register bare /gsd BEFORE directory check — always available if extension loads
  const helpPath = path.join(commandsDir, "help.md");
  pi.registerCommand("gsd", {
    description: "Show GSD help — same as /gsd:help",
    handler: async (args: string, ctx: any) => {
      let content: string;
      try {
        content = fs.readFileSync(helpPath, "utf8");
      } catch {
        ctx.ui.notify("Failed to read command file: " + helpPath, "error");
        return;
      }
      const { body } = parseCommand(content);
      if (!body || !body.trim()) {
        ctx.ui.notify("Command file has no content: " + helpPath, "error");
        return;
      }
      const transformed = resolver.transform(body, args?.trim() ?? "");
      pi.sendUserMessage(transformed);
    },
  });

  if (!fs.existsSync(commandsDir)) {
    return 0;
  }

  const files = fs
    .readdirSync(commandsDir)
    .filter((f: string) => f.endsWith(".md") && !f.endsWith(".bak"))
    .sort();

  let registered = 0;

  for (const file of files) {
    const commandSlug = file.replace(".md", "");
    const filePath = path.join(commandsDir, file);

    // Read at registration time for description (used in autocomplete)
    let meta: CommandMeta;
    try {
      const raw = fs.readFileSync(filePath, "utf8");
      meta = parseCommand(raw);
    } catch {
      continue; // Skip unreadable files
    }

    const cmdName = "gsd:" + commandSlug;
    const description =
      meta.description || "GSD: " + commandSlug.replace(/-/g, " ");

    pi.registerCommand(cmdName, {
      description,

      handler: async (args: string, ctx: any) => {
        // Re-read at invocation time so edits take effect without restart
        let content: string;
        try {
          content = fs.readFileSync(filePath, "utf8");
        } catch {
          ctx.ui.notify("Failed to read command file: " + filePath, "error");
          return;
        }

        const { body } = parseCommand(content);
        if (!body || !body.trim()) {
          ctx.ui.notify("Command file has no content: " + filePath, "error");
          return;
        }

        // Full transformation: rewrite paths -> transform @-includes -> inject args
        const transformed = resolver.transform(body, args?.trim() ?? "");

        // Send as user message — triggers the LLM to follow the GSD workflow
        pi.sendUserMessage(transformed);
      },
    });

    registered++;
  }

  return registered;
}
