/**
 * pi-gsd — Get Shit Done extension for Pi Coding Agent
 *
 * Extension entrypoint:
 *   1. Initializes GsdPathResolver (sets GSD_HOME)
 *   2. Registers /gsd:* slash commands via commands.ts
 *   3. Subscribes to 3 lifecycle events:
 *      - before_agent_start: injects GSD context into system prompt
 *      - tool_call: prepends export GSD_HOME for bash commands
 *      - session_start: sets GSD status indicator
 *
 * Generated by pi-gsd-maker.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { GsdPathResolver } from "./path-resolver.js";
import { registerGsdCommands } from "./commands.js";

export default function (pi: ExtensionAPI) {
  // Initialize path resolver — sets process.env.GSD_HOME via constructor
  const resolver = new GsdPathResolver();

  // Graceful degradation: gsd/ directory must exist
  if (!fs.existsSync(resolver.gsdHome)) {
    process.stderr.write("[pi-gsd] gsd/ directory not found at " + resolver.gsdHome + "\n");
    return;
  }

  // Graceful degradation: gsd/bin/gsd-tools.cjs must exist
  const toolsPath = path.join(resolver.gsdHome, "bin", "gsd-tools.cjs");
  if (!fs.existsSync(toolsPath)) {
    process.stderr.write("[pi-gsd] gsd/bin/gsd-tools.cjs not found at " + toolsPath + "\n");
    return;
  }

  // Register all /gsd:* commands + bare /gsd
  registerGsdCommands(pi, resolver);

  // --- System prompt injection for GSD projects ---
  pi.on("before_agent_start", async (event: any, ctx: any) => {
    // Only inject when .planning/ exists (indicates a GSD project)
    if (!fileExistsSync(path.join(ctx.cwd, ".planning"))) {
      return;
    }

    const gsdPrompt = buildGsdSystemPromptAddendum(resolver);
    return {
      systemPrompt: event.systemPrompt + gsdPrompt,
    };
  });

  // --- Rewrite $GSD_HOME in bash commands at runtime ---
  pi.on("tool_call", async (event: any) => {
    if (event.toolName !== "bash") return;
    const cmd = event.input?.command;
    if (!cmd) return;

    // Only intercept if the command references GSD_HOME or gsd-tools
    if (cmd.includes("GSD_HOME") || cmd.includes("gsd-tools")) {
      // Prepend export if not already present in this command
      if (!cmd.includes("export GSD_HOME=") && !cmd.includes("GSD_HOME=")) {
        event.input.command = `export GSD_HOME="${resolver.gsdHome}"\n${cmd}`;
      }
    }
  });

  // --- Status indicator for GSD projects ---
  pi.on("session_start", async (_event: any, ctx: any) => {
    if (fileExistsSync(path.join(ctx.cwd, ".planning", "STATE.md"))) {
      ctx.ui.setStatus("gsd", "GSD ●");
    }
  });
}

/**
 * Build the GSD-specific system prompt addendum.
 * Injected via before_agent_start when .planning/ directory exists.
 */
function buildGsdSystemPromptAddendum(resolver: GsdPathResolver): string {
  return `

## GSD (Get Shit Done) Project Context

This project uses the GSD spec-driven development system. Key information:

### File Locations
- **GSD runtime:** \`${resolver.gsdHome}/\`
- **gsd-tools CLI:** \`${resolver.gsdHome}/bin/gsd-tools.cjs\`
- **Workflows:** \`${resolver.gsdHome}/workflows/\`
- **References:** \`${resolver.gsdHome}/references/\`
- **Templates:** \`${resolver.gsdHome}/templates/\`
- **Project artifacts:** \`.planning/\` (in working directory)

### Path Resolution
When GSD commands, workflows, or agents reference files:
- \`@~/.claude/get-shit-done/\` → use \`${resolver.gsdHome}/\` instead
- \`$HOME/.claude/get-shit-done/\` → use \`${resolver.gsdHome}/\` instead
- \`$GSD_HOME/\` → use \`${resolver.gsdHome}/\`

When you encounter \`@path/to/file\` in an \`<execution_context>\` block, read that file using the Read tool.

### Tool Name Mapping (Claude Code → Pi)
GSD commands were originally written for Claude Code. Map these tool references:
- \`Task()\` → use the **subagent** tool with the appropriate \`gsd-*\` agent name
- \`AskUserQuestion\` → ask the user directly in your response text
- \`Read\`, \`Write\`, \`Edit\`, \`Bash\`, \`Grep\` → use the same-named Pi tools (lowercase in calls)
- \`Glob\` → use \`find\` tool or \`bash\` with \`find\`/\`ls\`
- \`TodoWrite\` → write TODO items to files directly
- \`WebFetch\` → use \`bash\` with \`curl\` if needed

### gsd-tools.cjs Usage
Run GSD tool commands via bash:
\`\`\`bash
node "${resolver.gsdHome}/bin/gsd-tools.cjs" <command> [args]
\`\`\`

### Subagent Spawning
When GSD workflows reference spawning agents (gsd-executor, gsd-planner, etc.),
use the subagent tool. GSD agents are available in the agents directory.
Example: \`subagent({ agent: "gsd-planner", task: "..." })\`
`;
}

function fileExistsSync(p: string): boolean {
  try {
    fs.statSync(p);
    return true;
  } catch {
    return false;
  }
}
