/**
 * GSD Path Resolver — runtime path resolution and content transformation.
 *
 * Rewrites GSD-specific paths to the installed package location,
 * transforms execution context blocks into Read instructions,
 * injects arguments, and provides the full transform pipeline.
 *
 * Generated by pi-gsd-maker.
 */

import path from "path";

export class GsdPathResolver {
  public readonly gsdHome: string;
  public readonly packageRoot: string;

  constructor() {
    // __dirname is available (CJS mode — no "type": "module" in package.json)
    // File lives at extensions/gsd/path-resolver.ts
    // So packageRoot = resolve(__dirname, '..', '..')
    this.packageRoot = path.resolve(__dirname, "..", "..");
    this.gsdHome = path.join(this.packageRoot, "gsd");
    process.env.GSD_HOME = this.gsdHome;
  }

  /**
   * Rewrite GSD-specific path patterns to the actual installed gsdHome path.
   * 4 patterns, applied in order (Rule 1 before Rule 3 to prevent @~ partial match).
   */
  rewritePaths(content: string): string {
    let result = content;
    // Rule 1: @~/.claude/get-shit-done/ → @{gsdHome}/ (preserves @ prefix)
    result = result.replace(/@~\/\.claude\/get-shit-done\//g, "@" + this.gsdHome + "/");
    // Rule 2: $HOME/.claude/get-shit-done/ → {gsdHome}/
    result = result.replace(/\$HOME\/\.claude\/get-shit-done\//g, this.gsdHome + "/");
    // Rule 3: ~/.claude/get-shit-done/ → {gsdHome}/
    result = result.replace(/~\/\.claude\/get-shit-done\//g, this.gsdHome + "/");
    // Rule 4: $GSD_HOME/ → {gsdHome}/ (expand variable from pre-transformed agents)
    result = result.replace(/\$GSD_HOME\//g, this.gsdHome + "/");
    return result;
  }

  /**
   * Transform <execution_context> blocks: convert @path lines to Read instructions.
   * Non-@ content preserved. Blocks with no @-includes pass through unchanged.
   */
  transformExecutionContext(content: string): string {
    return content.replace(
      /<execution_context>([\s\S]*?)<\/execution_context>/g,
      (_match: string, inner: string) => {
        const lines = inner.split("\n").map((line: string) => line.trim());
        const fileLines = lines.filter((line: string) => line.startsWith("@"));
        const nonFileLines = lines.filter((line: string) => line && !line.startsWith("@"));

        if (fileLines.length === 0) {
          return "<execution_context>" + inner + "</execution_context>";
        }

        const filePaths = fileLines.map((line: string) => line.slice(1));
        const readInstructions = filePaths.map((f: string) => "- " + f).join("\n");

        let block = "<execution_context>\n"
          + "IMPORTANT: Read each of these files using the Read tool before proceeding:\n"
          + readInstructions;

        if (nonFileLines.length > 0) {
          block += "\n\n" + nonFileLines.join("\n");
        }

        block += "\n</execution_context>";
        return block;
      }
    );
  }

  /**
   * Replace all $ARGUMENTS occurrences with provided args.
   * Uses split/join to avoid regex interpretation of replacement string.
   */
  injectArguments(content: string, args: string): string {
    return content.split("$ARGUMENTS").join(args);
  }

  /**
   * Full transform pipeline: rewrite paths → transform execution context → inject arguments.
   * Order matters: paths in @-includes get rewritten before context transform strips the @.
   */
  transform(content: string, args: string): string {
    let result = this.rewritePaths(content);
    result = this.transformExecutionContext(result);
    result = this.injectArguments(result, args);
    return result;
  }
}
