/**
 * Diagnostic formatters for test output.
 * formatFailure produces structured plain-text failure reports.
 * formatSummary produces per-suite counts, totals, and failure index.
 * Generated by pi-gsd-maker.
 */

export interface FailureOpts {
  file: string;
  expected: string;
  actual: string;
  why: string;
  evidence?: string;
}

export interface SuiteResult {
  name: string;
  passed: number;
  failed: number;
  duration: number;
  failures: Array<{ test: string; reason: string }>;
}

export interface SummaryOpts {
  suites: SuiteResult[];
  totalDuration: number;
}

/**
 * Format a test failure as structured plain text.
 * Includes FILE, EXPECTED, ACTUAL, WHY sections.
 * Includes EVIDENCE only when provided.
 * No ANSI escape codes.
 */
export function formatFailure(opts: FailureOpts): string {
  let output = "";
  output += "FILE: " + opts.file + "\n";
  output += "EXPECTED: " + opts.expected + "\n";
  output += "ACTUAL: " + opts.actual + "\n";
  output += "WHY: " + opts.why + "\n";
  if (opts.evidence !== undefined) {
    output += "EVIDENCE: " + opts.evidence + "\n";
  }
  return output;
}

/**
 * Format a test summary with per-suite counts, totals, duration, and failure index.
 * Failure index is omitted when all suites pass.
 */
export function formatSummary(opts: SummaryOpts): string {
  const lines: string[] = [];

  // Per-suite lines
  for (const suite of opts.suites) {
    lines.push(suite.name + ": " + suite.passed + " passed, " + suite.failed + " failed");
  }

  // Totals
  let totalPassed = 0;
  let totalFailed = 0;
  for (const suite of opts.suites) {
    totalPassed += suite.passed;
    totalFailed += suite.failed;
  }
  lines.push("Total: " + totalPassed + " passed, " + totalFailed + " failed");

  // Duration
  lines.push(opts.totalDuration + "ms");

  // Failure index (only when failures exist)
  const allFailures: Array<{ suite: string; test: string; reason: string }> = [];
  for (const suite of opts.suites) {
    for (const f of suite.failures) {
      allFailures.push({ suite: suite.name, test: f.test, reason: f.reason });
    }
  }

  if (allFailures.length > 0) {
    lines.push("FAILURE INDEX:");
    for (const f of allFailures) {
      lines.push("  " + f.suite + " > " + f.test + " \u2014 " + f.reason);
    }
  }

  return lines.join("\n") + "\n";
}
