/**
 * Lifecycle helpers for test environment isolation.
 * saveEnv/restoreEnv snapshot and restore GSD_HOME.
 * withTempDir creates an isolated temp directory with .planning/ inside.
 * Generated by pi-gsd-maker.
 */

import fs from "node:fs";
import path from "node:path";
import os from "node:os";

export interface EnvSnapshot {
  GSD_HOME: string | undefined;
}

/**
 * Capture current GSD_HOME value (may be undefined).
 */
export function saveEnv(): EnvSnapshot {
  return { GSD_HOME: process.env.GSD_HOME };
}

/**
 * Restore GSD_HOME to snapshotted value. Deletes if was undefined.
 * Does not affect other environment variables.
 */
export function restoreEnv(snap: EnvSnapshot): void {
  if (snap.GSD_HOME === undefined) {
    delete process.env.GSD_HOME;
  } else {
    process.env.GSD_HOME = snap.GSD_HOME;
  }
}

/**
 * Create a temp directory with .planning/ inside, call fn, clean up after.
 * Cleanup happens even if fn throws or rejects.
 * Supports both sync and async callbacks.
 */
export async function withTempDir(
  fn: (dir: string) => void | Promise<void>
): Promise<void> {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "gsd-test-"));
  fs.mkdirSync(path.join(dir, ".planning"));
  try {
    const result = fn(dir);
    if (result instanceof Promise) {
      await result;
    }
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}
