/**
 * Mock context factories for testing Pi extension behavior.
 * createMockContext provides cwd and UI recording.
 * createMockCommandContext extends with command session methods.
 * Generated by pi-gsd-maker.
 */

export interface MockUI {
  statusCalls: Array<{ key: string; text: string }>;
  notifyCalls: Array<{ message: string; type: string }>;
  setStatus(key: string, text: string): void;
  notify(message: string, type: string): void;
}

export interface MockContextResult {
  cwd: string;
  ui: MockUI;
  reset(): void;
}

export interface MockCommandContextResult extends MockContextResult {
  waitForIdle(): Promise<void>;
  newSession(): Promise<{ cancelled: boolean }>;
  fork(entryId: string): Promise<{ cancelled: boolean }>;
  navigateTree(targetId: string): Promise<{ cancelled: boolean }>;
  switchSession(path: string): Promise<{ cancelled: boolean }>;
  reload(): Promise<void>;
}

/**
 * Create a mock execution context with cwd and UI recording.
 */
export function createMockContext(opts?: { cwd?: string }): MockContextResult {
  const cwd = opts?.cwd ?? "/tmp/test-project";

  const ui: MockUI = {
    statusCalls: [],
    notifyCalls: [],
    setStatus(key: string, text: string): void {
      ui.statusCalls.push({ key, text });
    },
    notify(message: string, type: string): void {
      ui.notifyCalls.push({ message, type });
    },
  };

  return {
    cwd,
    ui,
    reset(): void {
      ui.statusCalls = [];
      ui.notifyCalls = [];
    },
  };
}

/**
 * Create a mock command context extending base context with session methods.
 */
export function createMockCommandContext(
  opts?: { cwd?: string }
): MockCommandContextResult {
  const base = createMockContext(opts);

  return {
    ...base,
    async waitForIdle(): Promise<void> {},
    async newSession(): Promise<{ cancelled: boolean }> {
      return { cancelled: false };
    },
    async fork(entryId: string): Promise<{ cancelled: boolean }> {
      return { cancelled: false };
    },
    async navigateTree(targetId: string): Promise<{ cancelled: boolean }> {
      return { cancelled: false };
    },
    async switchSession(path: string): Promise<{ cancelled: boolean }> {
      return { cancelled: false };
    },
    async reload(): Promise<void> {},
  };
}
