/**
 * MockExtensionAPI — simulates the Pi Extension API for testing.
 * Records subscriptions, commands, and messages.
 * Generated by pi-gsd-maker.
 */

export class MockExtensionAPI {
  /** Event name → handler array */
  subscriptions: Map<string, ((...args: any[]) => any)[]>;

  /** Command name → { description, handler } */
  commands: Map<string, { description: string; handler: (...args: any[]) => any }>;

  /** Recorded sendUserMessage calls */
  messages: Array<{ content: string; options?: Record<string, any> }>;

  constructor() {
    this.subscriptions = new Map();
    this.commands = new Map();
    this.messages = [];
  }

  /**
   * Subscribe to an event. Multiple handlers per event are supported.
   */
  on(eventName: string, handler: (...args: any[]) => any): void {
    if (!this.subscriptions.has(eventName)) {
      this.subscriptions.set(eventName, []);
    }
    this.subscriptions.get(eventName)!.push(handler);
  }

  /**
   * Register a slash command. Duplicates overwrite with stderr warning.
   */
  registerCommand(
    name: string,
    opts: { description: string; handler: (...args: any[]) => any }
  ): void {
    if (this.commands.has(name)) {
      process.stderr.write(`[mock] duplicate command: ${name}\n`);
    }
    this.commands.set(name, { description: opts.description, handler: opts.handler });
  }

  /**
   * Record a user message send.
   */
  sendUserMessage(content: string, options?: Record<string, any>): void {
    this.messages.push({ content, options });
  }

  /**
   * Fire an event, invoking all handlers in order. Returns last handler result.
   */
  async fireEvent(eventName: string, ...args: any[]): Promise<any> {
    const handlers = this.subscriptions.get(eventName);
    if (!handlers || handlers.length === 0) {
      process.stderr.write(`[mock] fireEvent for unregistered event: ${eventName}\n`);
      return undefined;
    }
    let result: any;
    for (const handler of handlers) {
      result = await handler(...args);
    }
    return result;
  }

  /**
   * Clear all recorded state.
   */
  reset(): void {
    this.subscriptions = new Map();
    this.commands = new Map();
    this.messages = [];
  }
}
